### ISSUE TITLE
Cannot use with Default Instance Name

### ISSUE THREAD

**Issue by snazy2000** [UretzkyZvi/Monitor-Applications-Using-SQL-Queries#1]
SCOM picks up the instance name is MSSQLSERVER but as this is the default instance you connect without the instance name, so when you try run a query it fails to connect

**Comment by UretzkyZvi** [comment]
I will fix this. 👍

**Comment by UretzkyZvi** [comment]
I fixed the problem, just extract the [QueryOleDbMonitorSetup.msi](https://github.com/UretzkyZvi/Monitor-Applications-Using-SQL-Queries/releases/download/v1.0.0.1/QueryOleDbMonitorSetup.msi
)
upgrade MP QueryOleDbMonitorTemplate in your environment by import the QueryOleDbMonitorTemplate.mpb file.

**Comment by snazy2000** [comment]
I've just tested this on MSSQLSERVER and still getting

![image](https://user-images.githubusercontent.com/1378836/30365255-16a42cce-985f-11e7-86d3-6d3ffa344fc3.png)

Could a more detailed error message be put out to event viewer or something? :)

Will SQL Auth support be added? 👍

**Comment by snazy2000** [comment]
When assigning Windows accounts to the "OleDB Query Moniotring Run As Profile" should the used for / selected object be the SCOM machine or the SQL server?

**Comment by UretzkyZvi** [comment]
@snazy2000 sorry, I will recompile the MSI..

**Comment by snazy2000** [comment]
@UretzkyZvi On subject of MSI file, it is not possible to "upgrade" you have to uninstall the old one and reinstall which is a bit of a pain

**Comment by UretzkyZvi** [comment]
I'm sorry for a late response,
@snazy2000  you totally right. 
This is why I updated the MP to support SQL Authentication.
Unfortunately, In my environment default authentication is windows.
So, it is difficult to test the solution, although, I was seen in SQL event login failure.
It will be very appreciated if you could give your feedback about that.

Thanks :) 
And this time I add a folder with compiled MPs.

**Comment by UretzkyZvi** [comment]
I'm closing the issue.
Thanks for your feedback 👍

**Comment by snazy2000** [comment]
Great work! I will test this out tomorrow! Thanks for fixing the issues and adding sql auth!!
